export const ANIME_LIST_REQUEST = 'ANIME_LIST_REQUEST';
export const ANIME_LIST_SUCCESS = 'ANIME_LIST_SUCCESS';
export const ANIME_LIST_FAIL = 'ANIME_LIST_FAIL';

export const MOVIES_LIST_REQUEST = 'MOVIES_LIST_REQUEST';
export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';
export const MOVIES_LIST_FAIL = 'MOVIES_LIST_FAIL';

export const SERIES_LIST_REQUEST = 'SERIES_LIST_REQUEST';
export const SERIES_LIST_SUCCESS = 'SERIES_LIST_SUCCESS';
export const SERIES_LIST_FAIL = 'SERIES_LIST_FAIL';
