# Generated by Django 5.1.5 on 2025-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='is_movie',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='price',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.CharField(choices=[('Series', 'Series'), ('Movie', 'Movie')], default='Series', max_length=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
