# Generated by Django 5.1.5 on 2025-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_anime_is_movie_remove_anime_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/'),
        ),
        migrations.AddField(
            model_name='reading',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reading_images/'),
        ),
    ]
