# Generated by Django 5.1.5 on 2025-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_registered_on_profile_subscribed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='anime_movies/'),
        ),
    ]
