# Generated by Django 5.1.5 on 2025-03-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_anime_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('upcoming_anime', 'Upcoming Anime'), ('upcoming_reading', 'Upcoming Reading'), ('trending_movie', 'Trending Movie'), ('trending_series', 'Trending Series'), ('trending_manga', 'Trending Manga'), ('trending_manhwa', 'Trending Manhwa'), ('trending_manhua', 'Trending Manhua'), ('popular', 'Most Popular')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
