# Generated by Django 5.1.5 on 2025-03-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='video_file',
        ),
    ]
