# Generated by Django 5.1.5 on 2025-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_delete_content_remove_anime_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('votes', models.JSONField(default=list)),
            ],
        ),
    ]
