# Generated by Django 5.1.5 on 2025-05-02 01:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_votepoll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votepoll',
            name='options',
        ),
        migrations.RemoveField(
            model_name='votepoll',
            name='votes',
        ),
        migrations.AddField(
            model_name='votepoll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='vote_images/')),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='media.votepoll')),
            ],
        ),
    ]
