# Generated by Django 5.1.5 on 2025-05-02 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_remove_votepoll_options_remove_votepoll_votes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteoption',
            name='votes',
        ),
        migrations.AddField(
            model_name='voteoption',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
