# Generated by Django 5.1.5 on 2025-05-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_voteoption_votes_voteoption_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteoption',
            name='voters',
        ),
        migrations.AddField(
            model_name='voteoption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
