# Generated by Django 5.1.5 on 2025-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('section_type', models.CharField(choices=[('upcoming_anime', 'Upcoming Anime'), ('upcoming_reading', 'Upcoming Reading'), ('trending_movie', 'Trending Movie'), ('trending_series', 'Trending Series'), ('trending_manga', 'Trending Manga'), ('trending_manhua', 'Trending Manhua'), ('trending_manhwa', 'Trending Manhwa'), ('most_popular', 'Most Popular')], max_length=50)),
                ('image', models.ImageField(upload_to='home_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
